### ISSUE TITLE
Search is inconsistent

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/projects-api#33]
The search appears inconsistent, in that it's not matching partial words, only whole words.

### Working

This search for `mobility` works and returns the expected project, using an auth token for `TonyJ / appirio123` in dev:

https://api.topcoder-dev.com/v5/projects?name=mobility&sort=lastActivityAt&status=active

![Screen_Shot_2020-04-27_at_06_59_31](https://user-images.githubusercontent.com/21790/80319612-aed44a00-8854-11ea-884a-69f1b0e3c677.png)

### Doesn't work

This search for `mobil`, which is a substring of `mobility` does *NOT* work

![Screen_Shot_2020-04-27_at_07_00_31](https://user-images.githubusercontent.com/21790/80319637-daefcb00-8854-11ea-9027-9fdce93cb2f8.png)

### Expectation

The search should:

* Be case insensitive (if it isn't already)
* Match partial strings, not just full words

**Comment by rootelement** [comment]
@vikasrohit Please check this out. This is to support search in the challenges.topcoder-dev.com UI. Let me know if we're doing something wrong with the way we're searching project names, or if you can get this on the list to fix soon.

**Comment by maxceem** [comment]
@rootelement @jmgasper there is support for searching by subwords also, the searching term can be wrapped into asterisks like `*mobil*`. The next request would find multiple projects
```
https://api.topcoder-dev.com/v5/projects/?sort=lastActivityAt+desc&perPage=20&page=1&name=*mobil*
```

**Comment by jmgasper** [comment]
@maxceem - I'll let @rootelement decide if we want that to be the default.  I don't see any use case where we'd be searching for whole-words *only*, so it doesn't make sense to have that be the default functionality.

**Comment by vikasrohit** [comment]
Thanks @jmgasper for raising the issue and thanks @maxceem for the answer.

@jmgasper @rootelement I am more inclined towards using wild cards while searching the term because that allows us to have both features: matching exact word and matching part of the word. And @jmgasper, I think there are cases where we need to match exact search terms instead of partials and infact we are using that right now in Connect e.g. when you are searching for all projects where a particular member is involved in, in such case you would tend to type the full handle of the member without any other wild cards and if we by default search for partial words, it would result in too many projects (consider a topcoder employee who has all projects access). We can not default to tokenize all possible sub words of a word. We do treat two different words in the search as separate key terms and search results are based on typical search engine algo where you would find projects with both words or single words.
Additionally, you also have option to force the order and presence of all words of a multi word search query by enclosing them in double quotes.
So, IMO, the current behavior is good for multiple use cases, many of which are already working in Connect. So, I would not like to alter this behavior unless we have very strong argument in favor it.

**Comment by jmgasper** [comment]
Ok - we'll update the challenge engine UI.
